package:
  name: bcbio-nextgen-vm
  version: '0.1.0a'

build:
  number: 100

source:
  git_url: https://github.com/chapmanb/bcbio-nextgen-vm.git
  git_tag: develop


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - bcbio-nextgen
    - elasticluster
    - nose
    - six
    - prettytable

test:
  imports:
    - bcbiovm.version
    - bcbiovm.provider.aws.aws_provider
    - bcbiovm.provider.azure.azure_provider
    - bcbiovm.container.docker.docker_container

about:
  home: https://github.com/chapmanb/bcbio-nextgen-vm
  license: MIT
  summary: Run bcbio-nextgen genomic sequencing analyses using isolated containers and virtual machines
