package: bcbio-nextgen
user: bcbio-dev

platform:
  - linux-64

engine:
 - python=2.7

install:
  - conda config --add channels https://conda.binstar.org/bcbio-dev

script:
  - conda build .

build_targets:
  files: conda
  channels: main