package:
  name: bcbio-nextgen
  version: '0.9.5a0'

build:
  number: 100

source:
  git_url: https://github.com/chapmanb/bcbio-nextgen.git
  git_tag: master


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - argparse [py26]
    - azure-sdk-for-python
    - biopython
    - boto
    - bx-python
    - cpat
    - cython
    - gffutils
    - ipyparallel
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - matplotlib
    - msgpack-python
    - numpy
    - pandas
    - progressbar
    - psutil
    - pybedtools
    - pysam
    - pythonpy
    - pyvcf
    - pyyaml
    - pyzmq
    - requests
    - seaborn
    - scipy
    - statsmodels
    - toolz
    - tornado

test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling and RNA-seq analysis
