package:
  name: bcbio-nextgen
  version: '0.9.6a'

build:
  number: 100

source:
  git_url: https://github.com/chapmanb/bcbio-nextgen.git
  git_tag: master


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - arrow
    - azure-sdk-for-python
    - bioblend
    - biopython
    - boto
    - click
    - cython
    - cyvcf2
    - fabric
    - fadapa
    - gffutils
    - ipyparallel
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - matplotlib
    - msgpack-python
    - nose
    - numpy
    - openpyxl
    - openssl
    - pandas
    - path.py
    - patsy
    - pip
    - pycrypto
    - progressbar
    - psutil
    - python-dateutil
    - pybedtools
    - pysam
    - pyvcf
    - pyyaml
    - pyzmq
    - reportlab
    - requests
    - scikit-learn
    - scipy
    - seaborn
    - seqcluster
    - sh
    - sqlalchemy
    - statsmodels
    - tabulate
    - toolz
    - tornado


test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling and RNA-seq analysis
