package:
  name: httplib2
  version: 0.8

source:
  fn: httplib2-0.8.tar.gz
  url: https://pypi.python.org/packages/source/h/httplib2/httplib2-0.8.tar.gz
  md5: 94cb8a3b196dfd19253c46609489d9f1

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - httplib2

about:
  home: http://code.google.com/p/httplib2/
  license: MIT License
