package:
  name: elasticluster
  version: '0.1.3bcbio'

source:
  git_url: https://github.com/chapmanb/elasticluster.git
  git_tag: bcbio

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ansible
    - azure
    - pycli
    - paramiko
    - voluptuous
    - configobj
    - boto
    - httplib2
    - google-api-python-client

test:
  # Python imports
  imports:
    - elasticluster
    - elasticluster.conf
    - elasticluster.main
    - elasticluster.providers.ansible_provider
    - elasticluster.providers.ec2_boto
    - elasticluster.providers.azure_provider

about:
  home: https://github.com/chapmanb/elasticluster
  license: GPL
  summary: Create, manage and setup computing clusters hosted on a public or private cloud infrastructure.